// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeApi.Data;

#nullable disable

namespace RecipeApi.Data.RecipeMigrations
{
    [DbContext(typeof(RecipeContext))]
    partial class RecipeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("RecipeApi.Model.FoodCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("FoodCategories");
                });

            modelBuilder.Entity("RecipeApi.Model.FoodRecipe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calorie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodCategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LOD")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Serve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Spicy")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FoodCategoryID");

                    b.ToTable("FoodRecipes");
                });

            modelBuilder.Entity("RecipeApi.Model.FoodRecipe", b =>
                {
                    b.HasOne("RecipeApi.Model.FoodCategory", "FoodCategory")
                        .WithMany("FoodRecipes")
                        .HasForeignKey("FoodCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoodCategory");
                });

            modelBuilder.Entity("RecipeApi.Model.FoodCategory", b =>
                {
                    b.Navigation("FoodRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
